source 'https://rubygems.org'

gem 'sinatra', :require => 'sinatra/base'
gem 'puma'
gem 'term-ansicolor', :require => 'term/ansicolor'
gem 'httpclient'
gem 'redis'
gem 'bol', :path => '/Users/ken/src/ruby/bol'

group :development, :test do
  gem 'selenium-webdriver'
  gem 'rack-test'
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec'
  gem 'cucumber'
  gem 'capybara'
  gem 'timecop'
  gem 'rack-colorized_logger'
end
